// app/layout.tsx
import Navbar from "@/Components/Navbar/Navbar";  // Importando o Navbar
import Footer from "@/Components/Footer/Footer";  // Importando o Footer
import "./globals.css";
import { NavbarProvider } from "@/Context/NavbarContext";
import Sidebar from "@/Components/Sidebar/Sidebar";
import { CartProvider } from "@/Context/CartContext";

export const metadata = {
  title: "DecaylStore",
  description: "Generated by luizevrs",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <CartProvider>
        <NavbarProvider>
          <Navbar /> {/* Navbar será mostrado em todas as páginas */}
          <Sidebar />
          <main>{children}</main> {/* Aqui o conteúdo da página será inserido */}
          <Footer /> {/* Footer será mostrado em todas as páginas */}
        </NavbarProvider> 
      </CartProvider> 
      </body>
    </html>
  );
}
